adb shell pm uninstall -k --user 0  com.sec.android.widgetapp.samsungapps
adb shell pm uninstall -k --user 0 com.samsung.android.app.FileShareClient
adb shell pm uninstall -k --user 0 com.samsung.android.securitylogagent
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.quota
adb shell pm uninstall -k --user 0 com.samsung.android.nearby.mediaserver
adb shell pm uninstall -k --user 0 com.samsung.android.app.assistantmenu
adb shell pm uninstall -k --user 0 com.hancom.office.hshow.viewer.hshow_viewer_apk
adb shell pm uninstall -k --user 0 com.lifevibes.trimapp
adb shell pm uninstall -k --user 0 com.samsung.android.MtpApplication
adb shell pm uninstall -k --user 0 com.samsung.aasaservice
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.spenv10
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.backup
adb shell pm uninstall -k --user 0 com.dropbox.android
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.proxy.memo
adb shell pm uninstall -k --user 0 com.samsung.shareshot
adb shell pm uninstall -k --user 0 com.samsung.android.app.FileShareServer
adb shell pm uninstall -k --user 0 com.hancom.androidpc.launcher.shared
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.proxy.calendar
adb shell pm uninstall -k --user 0 com.samsung.android.app.shareaccessibilitysettings
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.proxy.contacts
adb shell pm uninstall -k --user 0 com.hancom.office.hword.viewer.hword_apk
adb shell pm uninstall -k --user 0 com.samsung.scrc.idi.server
adb shell pm uninstall -k --user 0 com.sec.app.samsungprintservice
adb shell pm uninstall -k --user 0 com.samsung.android.service.travel
adb shell pm uninstall -k --user 0 com.samsung.android.mdm
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.professionalaudio.app.audioconnectionservice
adb shell pm uninstall -k --user 0 com.samsung.pickuptutorial
adb shell pm uninstall -k --user 0 com.netflix.mediaclient
adb shell pm uninstall -k --user 0 com.samsung.klmsagent
adb shell pm uninstall -k --user 0 com.osp.app.signin
adb shell pm uninstall -k --user 0 com.samsung.SMT
adb shell pm uninstall -k --user 0 com.samsung.everglades.video
adb shell pm uninstall -k --user 0 com.samsung.android.allshare.service.mediashare
adb shell pm uninstall -k --user 0 com.hancom.androidpc.viewer.launcher
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.auth
adb shell pm uninstall -k --user 0 com.samsung.palmswipetutorial
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.sync
adb shell pm uninstall -k --user 0 com.samsung.clipboardsaveservice
adb shell pm uninstall -k --user 0 com.samsung.android.clipboarduiservice
adb shell pm uninstall -k --user 0 com.sec.kidsplat.installer
adb shell pm uninstall -k --user 0 com.samsung.knox.rcp.components
adb shell pm uninstall -k --user 0 com.samsung.android.visualeffect.res
adb shell pm uninstall -k --user 0 com.samsung.android.scloud.proxy.sbrowser
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.samsung.safetyinformation
adb shell pm uninstall -k --user 0 com.vlingo.midas
adb shell pm uninstall -k --user 0 com.hancom.androidpc.appwidget
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
adb shell pm uninstall -k --user 0 com.hancom.office.hcell.viewer.hcell_viewer_apk
adb shell pm uninstall -k --user 0 com.samsung.android.allshare.service.fileshare
adb shell pm uninstall -k --user 0 com.samsung.sec.android.application.csc
adb shell pm uninstall -k --user 0 com.sec.android.app.SamsungContentsAgent
adb shell pm uninstall -k --user 0 com.samsung.android.bbc.bbcagent
adb shell pm uninstall -k --user 0 kr.co.rightbrain.ScreenSaver.Galaxy_Tab4_10
adb shell pm uninstall -k --user 0 com.samsung.android.app.memo
adb shell pm uninstall -k --user 0 com.samsung.android.app.accesscontrol
adb shell pm uninstall -k --user 0 com.samsung.android.asksmanager
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.professionalaudio.utility.jammonitor
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.SPlannerAppWidget
adb shell pm uninstall -k --user 0 com.samsung.helphub
adb shell pm uninstall -k --user 0 com.android.musicfx
adb shell pm uninstall -k --user 0 com.samsung.android.intelligenceservice
